#travis configuration for coverage testing
language: c
os: linux

#sudo: false # only for faster builds
before_install:
- sudo apt-get update
- sudo apt-get -y install tree
- sudo apt-get install -y fuse
- sudo apt-get install -y libfuse-dev

install:
- cd ${TRAVIS_BUILD_DIR}
# install latest LCOV (1.9 was failing for me) [1]

- wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
- tar xf lcov_1.11.orig.tar.gz
- sudo make -C lcov-1.11/ install

# install lcov to coveralls conversion + upload tool
- gem install coveralls-lcov


before_script: 
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --zerocounters

# Compiler selection
compiler:
  - clang
  - gcc


# Build steps
script: 
  - cd ${TRAVIS_BUILD_DIR}
  - aclocal
  - autoconf
  - autoheader
  - touch AUTHORS NEWS ChangeLog README
  - automake --add-missing
  - ./configure
  - make && ./test-library.out
  - tree


after_success:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture --output-file coverage.info # capture coverage info
- lcov --remove coverage.info 'tests/*' '/usr/*' 'test-library*' --output-file coverage.info # filter out system and test code
- lcov --list coverage.info # debug before upload
#- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls.. for a private repo using a token
- coveralls-lcov  coverage.info #for open source 
